name: Build Android App

on:
  pull_request:
    types: [opened, synchronize, labeled]
  workflow_dispatch:
    inputs:
      build_type:
        description: "Debug or Release"
        required: true
        default: "release"
        type: choice
        options:
          - release
          - debug

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      ((github.event.action == 'synchronize') && contains(github.event.pull_request.labels.*.name, 'build-apk')) ||
      ((github.event.action == 'labeled') && (github.event.label.name == 'build-apk')) ||
      (github.event_name == 'workflow_dispatch')
    env:
      FLAVOR: prod
      BUILD_TYPE: ${{ inputs.build_type || 'release' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup properties
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: |
          properties_file="./${FLAVOR}.properties"
          echo Setup "$properties_file"
          echo MAPS_API_KEY=$MAPS_API_KEY >> $properties_file

      - name: Build With Gradle
        # 環境変数からTask名を組み立てる（キャメルケースでassembleProdDebugのようになる）
        run: |
          task=$(echo "assemble_${FLAVOR}_${BUILD_TYPE}" | sed -r 's/(_)(.)/\u\2/g')
          echo $task
          ./gradlew $task

      # アーティファクトとして保存
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.FLAVOR }}-${{ env.BUILD_TYPE }}.apk
          path: app/build/outputs/apk/${{ env.FLAVOR }}/${{ env.BUILD_TYPE }}/*.apk

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: ${{ github.event.pull_request.body }}
      #     tag_name: ${{ github.event.pull_request.title }}
      #     generate_release_notes: true
      #     files: app/build/outputs/apk/${{ env.FLAVOR }}/${{ env.BUILD_TYPE }}/app-${{ env.FLAVOR }}-${{ env.BUILD_TYPE }}.apk
